### ISSUE TITLE
Disposição de metodos

### ISSUE THREAD

**Issue by amadeu01** [Lipemenezes/cpf-api#2]
https://github.com/Lipemenezes/cpf-api/blob/03e2d12ceab21e5e73bdfe47b4e8abc7226ce166/app/controllers/cpf.js#L25-L40

> ## “Reading Code from Top to Bottom: The Stepdown Rule

 
> We want the code to read like a top-down narrative.
> We want every function to be followed by those at the next level of abstraction so that we can read the program, descending one level of abstraction at a time as we read down the list of functions. I call this The Step-down Rule.

> To say this differently, we want to be able to read the program as though it were a set of TO paragraphs, each of which is describing the current level of abstraction and referencing subsequent TO paragraphs at the next level down.

> To include the setups and teardowns, we include setups, then we include the test page content, and then we include the teardowns.
 
> To include the setups, we include the suite setup if this is a suite, then we include the regular setup.”

Excerpt From: Martin, Robert C. “Clean Code: A Handbook of Agile Software Craftsmanship.” Apple Books. 

Observa que você coloca um metodo acima que só é usando na parte mais para baixo.

**Comment by Lipemenezes** [comment]
uma boa prática no Node é deixar o export no fim do arquivo, então na minha opinião, isso não se aplica nesse caso.

eu poderia mover essas funções para o model, mas estou avaliando ainda.

valeu pela análise.
